package com.filiaiev.orderservice.resource.entity;

public enum OrderStatusRO {

    AWAITING_WAREHOUSE_SHIPPING,
    RECEIVED_AT_WAREHOUSE,
    DEPARTED_FROM_WAREHOUSE,
    ARRIVED_AT_ORIGIN_AIRPORT,
    TERMINAL_PROCESSING,
    READY_FOR_LOADING,
    LOADED,
    ON_ITS_WAY,
    ARRIVED_AT_DESTINATION_AIRPORT,
    READY_FOR_COLLECTION,
    TERMINATED
}
